services:
  - name: elsip-backend
    type: web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: elsip-db
          property: connectionString
      - key: NODE_ENV
        value: production

  - name: elsip-admin
    type: web
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: API_URL
        value: https://elsip-backend.onrender.com
      - key: NODE_ENV
        value: production

  - name: elsip-frontend
    type: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://elsip-backend.onrender.com

databases:
  - name: elsip-db
    plan: free
    databaseName: elsip
    user: elsip_user
